### ISSUE TITLE
Identification Icon

### ISSUE THREAD

**Issue by coreytukios** [codeat3/blade-pepicons#5]
The identification icon has a small issue. In it's current form on 1.3 there's this: 
`<rect x="2" y="4.5" width="16" height="11" rx="2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>`
That is covering up the entire icon. If you remove that it works.

Current version:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M9.5 8H12" stroke="currentColor" stroke-linecap="round"/>
                        <path d="M9.5 11.75L14.5 11.75" stroke="currentColor" stroke-linecap="round"/>
                        <path d="M9.5 9.25H12H14.5M9.5 10.5H14.5" stroke="currentColor" stroke-linecap="round"/>
                        <circle cx="6.5" cy="9.25" r="1.25" fill="currentColor"/>
                        <path d="M8 11.6275C8 12.2582 7.32843 12.1985 6.5 12.1985C5.67157 12.1985 5 12.2582 5 11.6275C5 10.9968 5.67157 10.2 6.5 10.2C7.32843 10.2 8 10.9968 8 11.6275Z" fill="currentColor"/>
                        <rect x="2" y="4.5" width="16" height="11" rx="2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M9 8C9 7.72386 9.22386 7.5 9.5 7.5H12C12.2761 7.5 12.5 7.72386 12.5 8C12.5 8.27614 12.2761 8.5 12 8.5H9.5C9.22386 8.5 9 8.27614 9 8Z" fill="currentColor"/>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M9 11.75C9 11.4739 9.22386 11.25 9.5 11.25L14.5 11.25C14.7761 11.25 15 11.4739 15 11.75C15 12.0261 14.7761 12.25 14.5 12.25L9.5 12.25C9.22386 12.25 9 12.0261 9 11.75Z" fill="currentColor"/>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M9 9.25C9 8.97386 9.22386 8.75 9.5 8.75H14.5C14.7761 8.75 15 8.97386 15 9.25C15 9.52614 14.7761 9.75 14.5 9.75H9.5C9.22386 9.75 9 9.52614 9 9.25ZM9 10.5C9 10.2239 9.22386 10 9.5 10H14.5C14.7761 10 15 10.2239 15 10.5C15 10.7761 14.7761 11 14.5 11H9.5C9.22386 11 9 10.7761 9 10.5Z" fill="currentColor"/>
                        <path d="M7.75 9.25C7.75 9.94036 7.19036 10.5 6.5 10.5C5.80964 10.5 5.25 9.94036 5.25 9.25C5.25 8.55964 5.80964 8 6.5 8C7.19036 8 7.75 8.55964 7.75 9.25Z" fill="currentColor"/><path d="M8 11.6275C8 12.2582 7.32843 12.1985 6.5 12.1985C5.67157 12.1985 5 12.2582 5 11.6275C5 10.9968 5.67157 10.2 6.5 10.2C7.32843 10.2 8 10.9968 8 11.6275Z" fill="currentColor"/>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M1 6.5C1 4.84315 2.34315 3.5 4 3.5H16C17.6569 3.5 19 4.84315 19 6.5V13.5C19 15.1569 17.6569 16.5 16 16.5H4C2.34315 16.5 1 15.1569 1 13.5V6.5ZM4 5.5C3.44772 5.5 3 5.94772 3 6.5V13.5C3 14.0523 3.44772 14.5 4 14.5H16C16.5523 14.5 17 14.0523 17 13.5V6.5C17 5.94772 16.5523 5.5 16 5.5H4Z" fill="currentColor"/>
                    </svg>` 

Corrected version:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                        <path d="M9.5 8H12" stroke="currentColor" stroke-linecap="round"/>
                        <path d="M9.5 11.75L14.5 11.75" stroke="currentColor" stroke-linecap="round"/>
                        <path d="M9.5 9.25H12H14.5M9.5 10.5H14.5" stroke="currentColor" stroke-linecap="round"/>
                        <circle cx="6.5" cy="9.25" r="1.25" fill="currentColor"/>
                        <path d="M8 11.6275C8 12.2582 7.32843 12.1985 6.5 12.1985C5.67157 12.1985 5 12.2582 5 11.6275C5 10.9968 5.67157 10.2 6.5 10.2C7.32843 10.2 8 10.9968 8 11.6275Z" fill="currentColor"/>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M9 8C9 7.72386 9.22386 7.5 9.5 7.5H12C12.2761 7.5 12.5 7.72386 12.5 8C12.5 8.27614 12.2761 8.5 12 8.5H9.5C9.22386 8.5 9 8.27614 9 8Z" fill="currentColor"/>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M9 11.75C9 11.4739 9.22386 11.25 9.5 11.25L14.5 11.25C14.7761 11.25 15 11.4739 15 11.75C15 12.0261 14.7761 12.25 14.5 12.25L9.5 12.25C9.22386 12.25 9 12.0261 9 11.75Z" fill="currentColor"/>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M9 9.25C9 8.97386 9.22386 8.75 9.5 8.75H14.5C14.7761 8.75 15 8.97386 15 9.25C15 9.52614 14.7761 9.75 14.5 9.75H9.5C9.22386 9.75 9 9.52614 9 9.25ZM9 10.5C9 10.2239 9.22386 10 9.5 10H14.5C14.7761 10 15 10.2239 15 10.5C15 10.7761 14.7761 11 14.5 11H9.5C9.22386 11 9 10.7761 9 10.5Z" fill="currentColor"/>
                        <path d="M7.75 9.25C7.75 9.94036 7.19036 10.5 6.5 10.5C5.80964 10.5 5.25 9.94036 5.25 9.25C5.25 8.55964 5.80964 8 6.5 8C7.19036 8 7.75 8.55964 7.75 9.25Z" fill="currentColor"/><path d="M8 11.6275C8 12.2582 7.32843 12.1985 6.5 12.1985C5.67157 12.1985 5 12.2582 5 11.6275C5 10.9968 5.67157 10.2 6.5 10.2C7.32843 10.2 8 10.9968 8 11.6275Z" fill="currentColor"/>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M1 6.5C1 4.84315 2.34315 3.5 4 3.5H16C17.6569 3.5 19 4.84315 19 6.5V13.5C19 15.1569 17.6569 16.5 16 16.5H4C2.34315 16.5 1 15.1569 1 13.5V6.5ZM4 5.5C3.44772 5.5 3 5.94772 3 6.5V13.5C3 14.0523 3.44772 14.5 4 14.5H16C16.5523 14.5 17 14.0523 17 13.5V6.5C17 5.94772 16.5523 5.5 16 5.5H4Z" fill="currentColor"/>
                    </svg>`

**Comment by swapnilsarwe** [comment]
@coreytukios 
Thanks for pointing out. Will have a look at it tomorrow morning & fix the issue ASAP.

**Comment by swapnilsarwe** [comment]
@coreytukios - kindly update the version to `1.3.1` to get the correct icons
